### PR TITLE
Various UX/UI improvements

### PR DESCRIPTION
**Pull request by blambeau**
Just my 5 cents. Maybe some choices are arguable...

### CODE REVIEW

**Comment by blambeau** [comment]
@GuillaumeDerval the last commit might actually break the second button.

I could not test on my computer (would you add a README to bootstrap the python stuff? I'm a rubyist)

**Comment by GuillaumeDerval** [comment]
The python app is litteraly a counter that I use to count the number of views (without storing logs about the referrer), and is not needed to use the app locally. 

The main app is just plain HTML, and running a local server simply works: ```python -m http.server 8000```

**Comment by GuillaumeDerval** [comment]
LGTM :)

**Comment by blambeau** [comment]
> The python app is litteraly a counter that I use to count the number of views (without storing logs about the referrer), and is not needed to use the app locally.
> 
> The main app is just plain HTML, and running a local server simply works: `python -m http.server 8000`

I've got a simpleanalytics.com account if you want.

**Pull request merged**
